import type { PatientRecord, NewPatientRecord } from '../types';

// INSTRUCCIONES:
// 1. Despliega tu script de Google Apps (Code.gs) como una aplicación web.
// 2. Otorga acceso a "Cualquier persona".
// 3. Copia la URL de la aplicación web desplegada.
// 4. Descomenta la siguiente línea y pega tu URL.
const APPS_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbzHubY5b4xWdj3uN9hs5458qZDQv1f79LMeftvcJvtyJaergrKf1K_QQFRSj5CVF4Kw/exec';

// --- INICIO DEL CÓDIGO DE SIMULACIÓN (MOCK) ---
// Este código simula el backend. Reemplázalo con llamadas 'fetch' reales una vez que tengas tu URL.

let mockData: PatientRecord[] = [
    {
        RowID: '1721352101000',
        FECHA: '2025-01-07',
        NOMBRE: 'JOSE ANGEL SANCHEZ SORTO',
        EDAD: 69,
        SEXO: 'Masculino',
        REGISTRO: '16006-24',
        DIAGNOSTICO: 'MET PULMONARES',
        FACTOR_DE_RIESGO: 'SIN COMORBIDOS',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DRA. ORANTE',
        GENEXPERT_LAVADO: 'Trace Detected',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'CANDIDA ALBICANS',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'PENDIENTE',
        CULTIVO_NO_BAAR_ESPUTO: 'PENDIENTE',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'BIOPSIA PLEURAL',
        OBSERVACION: 'SE RECIBIO MUESTRA PARA ESTUDIO',
        DESTINO_PACIENTE: 'FALLECIDO',
        NUMERO_BIOPSIA: '187',
        DATO_ADICIONAL_1: 'C78.0',
        DATO_ADICIONAL_2: 'Metástasis en pulmón',
    },
    {
        RowID: '1721352102000',
        FECHA: '2025-01-09',
        NOMBRE: 'GUMERCINDA ROGEL',
        EDAD: 76,
        SEXO: 'Femenino',
        REGISTRO: '15228-24',
        DIAGNOSTICO: 'D/CA VRS METS PLEURAL',
        FACTOR_DE_RIESGO: 'HTA',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DRA. GONZALEZ',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'NEGATIVO',
        NO_BAAR_LAVADO: 'PSEUDOMONAS AERUGINOSA',
        GENEXPERT_ESPUTO: 'PENDIENTE',
        CULTIVO_NO_BAAR_ESPUTO: 'PENDIENTE',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Adenocarcinoma primario',
        OBSERVACION: 'Ingresa para estudio de masa pulmonar.',
        DESTINO_PACIENTE: 'REFERIDA A ONCOLOGIA',
        NUMERO_BIOPSIA: '201',
        DATO_ADICIONAL_1: 'C34.9',
        DATO_ADICIONAL_2: 'Neoplasia maligna de bronquios o pulmones',
    },
    {
        RowID: '1721352103000',
        FECHA: '2025-01-10',
        NOMBRE: 'NARCISO LOPEZ',
        EDAD: 74,
        SEXO: 'Masculino',
        REGISTRO: '4742-22',
        DIAGNOSTICO: 'EPID + TB CLINICA',
        FACTOR_DE_RIESGO: 'DM, HTA, ANTECEDENTE DE TB',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DRA. ORANTE',
        GENEXPERT_LAVADO: 'Trace Detected',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'CANDIDA ALBICANS',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'NEGATIVO',
        BIOPSIA: 'No',
        RESULTADO_BIOPSIA: '',
        OBSERVACION: 'Paciente con tratamiento previo para TB.',
        DESTINO_PACIENTE: 'SEGUIMIENTO',
        NUMERO_BIOPSIA: 'N/A',
        DATO_ADICIONAL_1: 'J84.9',
        DATO_ADICIONAL_2: 'Enfermedad pulmonar intersticial',
    },
    {
        RowID: '1721352104000',
        FECHA: '2025-01-15',
        NOMBRE: 'RANULFO MEJIA GUATEMALA',
        EDAD: 84,
        SEXO: 'Masculino',
        REGISTRO: '986-25',
        DIAGNOSTICO: 'S/ METS PULMONAR',
        FACTOR_DE_RIESGO: 'SIN COMORBIDOS',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DRA. ORANTES',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'CANDIDA ALBICANS',
        NO_BAAR_LAVADO: 'E.COLI, E. AEROGENES',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'NEGATIVO',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'No evidencia de malignidad',
        OBSERVACION: 'Biopsias de Carina: sin atipia.',
        DESTINO_PACIENTE: 'ALTA',
        NUMERO_BIOPSIA: '318',
        DATO_ADICIONAL_1: 'C78.0',
        DATO_ADICIONAL_2: 'Metástasis en pulmón',
    },
    {
        RowID: '1721352105000',
        FECHA: '2025-01-16',
        NOMBRE: 'VICTOR MANUEL ROQUE',
        EDAD: 79,
        SEXO: 'Masculino',
        REGISTRO: '1060-25',
        DIAGNOSTICO: 'S/ NEOPLASIA',
        FACTOR_DE_RIESGO: 'HTA',
        PROCEDENCIA: 'EMERGENCIA',
        MEDICO_ENCARGADO: 'DR. ENRIQUEZ',
        GENEXPERT_LAVADO: 'Trace Detected',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'NEGATIVO',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'NEGATIVO',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Carcinoma poco diferenciado',
        OBSERVACION: 'Reporte 16 Enero 2025.',
        DESTINO_PACIENTE: 'FALLECIDO',
        NUMERO_BIOPSIA: '341',
        DATO_ADICIONAL_1: 'C34.1',
        DATO_ADICIONAL_2: 'Neoplasia lóbulo superior',
    },
    {
        RowID: '1721352106000',
        FECHA: '2025-01-20',
        NOMBRE: 'VICTORINO ANTONIO RAMIREZ',
        EDAD: 73,
        SEXO: 'Masculino',
        REGISTRO: '8650-21',
        DIAGNOSTICO: 'HEMOPTISIS',
        FACTOR_DE_RIESGO: 'DM',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DRA. GONZALEZ',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'NEGATIVO',
        NO_BAAR_LAVADO: 'ENTEROBACTER AEROGENES, STAPHYLOCOCCUS AUREUS',
        GENEXPERT_ESPUTO: 'PENDIENTE',
        CULTIVO_NO_BAAR_ESPUTO: 'PENDIENTE',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Inflamación crónica',
        OBSERVACION: 'Muestra minúscula corresponde a mucosa.',
        DESTINO_PACIENTE: 'PROGRAMA ASTRAZENECA',
        NUMERO_BIOPSIA: '500',
        DATO_ADICIONAL_1: 'R04.2',
        DATO_ADICIONAL_2: 'Hemoptisis',
    },
    {
        RowID: '1721352107000',
        FECHA: '2025-01-21',
        NOMBRE: 'ALMA ROSA QUINTANILLA',
        EDAD: 63,
        SEXO: 'Femenino',
        REGISTRO: '5984-24',
        DIAGNOSTICO: 'CONSOLIDACION PULMONAR',
        FACTOR_DE_RIESGO: 'HTA, ERC',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DR. FIGUEROA',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'PENDIENTE',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'NEGATIVO',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Inflamación crónica',
        OBSERVACION: 'Tumoración en espolón de tronco intermediario.',
        DESTINO_PACIENTE: 'SEGUIMIENTO',
        NUMERO_BIOPSIA: '534',
        DATO_ADICIONAL_1: 'J18.0',
        DATO_ADICIONAL_2: 'Bronconeumonía',
    },
    {
        RowID: '1721352108000',
        FECHA: '2025-01-22',
        NOMBRE: 'DIDO CISNERO',
        EDAD: 53,
        SEXO: 'Masculino',
        REGISTRO: '1663-25',
        DIAGNOSTICO: 'S/TB PULMONAR',
        FACTOR_DE_RIESGO: 'PRIVADO DE LIBERTAD',
        PROCEDENCIA: 'H. METAPAN',
        MEDICO_ENCARGADO: 'DR. FIGUEROA',
        GENEXPERT_LAVADO: 'DETECTED VERY LOW',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'CANDIDA ALBICANS',
        NO_BAAR_LAVADO: 'STAPHYLOCOCCUS AUREUS',
        GENEXPERT_ESPUTO: 'PENDIENTE',
        CULTIVO_NO_BAAR_ESPUTO: 'PENDIENTE',
        BIOPSIA: 'No',
        RESULTADO_BIOPSIA: '',
        OBSERVACION: '',
        DESTINO_PACIENTE: 'NO ACEPTA',
        NUMERO_BIOPSIA: 'N/A',
        DATO_ADICIONAL_1: 'A15.0',
        DATO_ADICIONAL_2: 'Tuberculosis pulmonar',
    },
    {
        RowID: '1721352109000',
        FECHA: '2025-01-23',
        NOMBRE: 'SANDRA ELIZABETH ESCOBAR',
        EDAD: 53,
        SEXO: 'Femenino',
        REGISTRO: '8316-23',
        DIAGNOSTICO: 'NEUMONIA / EPID / TB',
        FACTOR_DE_RIESGO: 'HTA',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DR. FIGUEROA',
        GENEXPERT_LAVADO: 'Trace Detected',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'CANDIDA ALBICANS',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'STREPTOCOCCUS SALIVARIUS',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Parenquima pulmonar',
        OBSERVACION: 'Estudio de parénquima.',
        DESTINO_PACIENTE: 'SEGUIMIENTO',
        NUMERO_BIOPSIA: '591',
        DATO_ADICIONAL_1: 'J18.9',
        DATO_ADICIONAL_2: 'Neumonía no especificada',
    },
    {
        RowID: '1721352110000',
        FECHA: '2025-01-24',
        NOMBRE: 'WILLIAN EZEQUIEL CORTEZ',
        EDAD: 27,
        SEXO: 'Masculino',
        REGISTRO: '1595-25',
        DIAGNOSTICO: 'MULTIPLES NODULOS',
        FACTOR_DE_RIESGO: 'SIN COMORBIDOS',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DR. FIGUEROA',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'PENDIENTE',
        NO_BAAR_LAVADO: 'KLEBSIELLA PNEUMONIAE',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'NEGATIVO',
        BIOPSIA: 'No',
        RESULTADO_BIOPSIA: '',
        OBSERVACION: 'Paciente estable.',
        DESTINO_PACIENTE: 'ALTA',
        NUMERO_BIOPSIA: 'N/A',
        DATO_ADICIONAL_1: 'R91.1',
        DATO_ADICIONAL_2: 'Nódulo pulmonar solitario',
    },
    {
        RowID: '1721352111000',
        FECHA: '2025-01-28',
        NOMBRE: 'HECTOR ANTONIO PEREZ',
        EDAD: 49,
        SEXO: 'Masculino',
        REGISTRO: '2029-25',
        DIAGNOSTICO: 'S/TB MILIAR',
        FACTOR_DE_RIESGO: 'ETILISTA',
        PROCEDENCIA: 'H. SAN RAFAEL',
        MEDICO_ENCARGADO: 'DRA. DURAN',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'PENDIENTE',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'NEGATIVO',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Parenquima pulmonar',
        OBSERVACION: '',
        DESTINO_PACIENTE: 'SEGUIMIENTO',
        NUMERO_BIOPSIA: '717',
        DATO_ADICIONAL_1: 'A19.9',
        DATO_ADICIONAL_2: 'Tuberculosis miliar, sin especificar',
    },
    {
        RowID: '1721352112000',
        FECHA: '2025-01-29',
        NOMBRE: 'TEODORO SALVADOR CASTRO',
        EDAD: 69,
        SEXO: 'Masculino',
        REGISTRO: '1587-25',
        DIAGNOSTICO: 'S/NEOPLASIA PULMONAR',
        FACTOR_DE_RIESGO: 'EPOC',
        PROCEDENCIA: 'NEUMOLOGIA',
        MEDICO_ENCARGADO: 'DRA. ORANTE',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'PENDIENTE',
        NO_BAAR_LAVADO: 'STREPTOCOCCUS SANGUINIS',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'STAPHYLOCOCCUS HAEMOLYTICUS',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Inflamación crónica',
        OBSERVACION: 'NO LLEGO MUESTRA A PATOLOGIA',
        DESTINO_PACIENTE: 'FALLECIDO',
        NUMERO_BIOPSIA: '741',
        DATO_ADICIONAL_1: 'C34.9',
        DATO_ADICIONAL_2: 'Neoplasia maligna de bronquios o pulmones',
    },
    {
        RowID: '1721352113000',
        FECHA: '2025-01-30',
        NOMBRE: 'JACQUELIN XIOMARA FLORES',
        EDAD: 28,
        SEXO: 'Femenino',
        REGISTRO: '2152-25',
        DIAGNOSTICO: 'S/METS PULMONARES',
        FACTOR_DE_RIESGO: 'CANCER DE MAMA',
        PROCEDENCIA: 'H. AHUACHAPAN',
        MEDICO_ENCARGADO: 'DRA. ARTEAGA',
        GENEXPERT_LAVADO: 'DETECTED VERY LOW',
        CULTIVO_TBC: 'PENDIENTE',
        MICOLOGICO_LAVADO: 'CANDIDA ALBICANS',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'PENDIENTE',
        CULTIVO_NO_BAAR_ESPUTO: 'PENDIENTE',
        BIOPSIA: 'No',
        RESULTADO_BIOPSIA: '',
        OBSERVACION: 'Paciente refiere mejoría clínica.',
        DESTINO_PACIENTE: 'REFERIDA A ONCOLOGIA',
        NUMERO_BIOPSIA: 'N/A',
        DATO_ADICIONAL_1: 'C78.0',
        DATO_ADICIONAL_2: 'Metástasis en pulmón',
    },
    {
        RowID: '1721352114000',
        FECHA: '2025-02-01',
        NOMBRE: 'MARIA ELENA CAMPOS',
        EDAD: 55,
        SEXO: 'Femenino',
        REGISTRO: '3456-25',
        DIAGNOSTICO: 'Fibrosis Pulmonar',
        FACTOR_DE_RIESGO: 'Artritis Reumatoide',
        PROCEDENCIA: 'REUMATOLOGIA',
        MEDICO_ENCARGADO: 'DR. SANDOVAL',
        GENEXPERT_LAVADO: 'NOT DETECTED',
        CULTIVO_TBC: 'NEGATIVO',
        MICOLOGICO_LAVADO: 'NEGATIVO',
        NO_BAAR_LAVADO: 'NEGATIVO',
        GENEXPERT_ESPUTO: 'NO SE REALIZO',
        CULTIVO_NO_BAAR_ESPUTO: 'NO SE REALIZO',
        BIOPSIA: 'Sí',
        RESULTADO_BIOPSIA: 'Patrón de neumonía intersticial usual (NIU).',
        OBSERVACION: 'Compatible con el diagnóstico de fibrosis pulmonar idiopática.',
        DESTINO_PACIENTE: 'SEGUIMIENTO POR REUMATOLOGIA',
        NUMERO_BIOPSIA: '812',
        DATO_ADICIONAL_1: 'J84.1',
        DATO_ADICIONAL_2: 'Otras enfermedades pulmonares intersticiales con fibrosis',
    },
    {
        RowID: '1721352115000',
        FECHA: '2025-02-03',
        NOMBRE: 'CARLOS ALBERTO RIVAS',
        EDAD: 62,
        SEXO: 'Masculino',
        REGISTRO: '7890-25',
        DIAGNOSTICO: 'EPOC Exacerbado',
        FACTOR_DE_RIESGO: 'Tabaquismo Severo',
        PROCEDENCIA: 'EMERGENCIA',
        MEDICO_ENCARGADO: 'DR. CAÑAS',
        GENEXPERT_LAVADO: 'NO SE REALIZO',
        CULTIVO_TBC: 'NO SE REALIZO',
        MICOLOGICO_LAVADO: 'NO SE REALIZO',
        NO_BAAR_LAVADO: 'NO SE REALIZO',
        GENEXPERT_ESPUTO: 'NOT DETECTED',
        CULTIVO_NO_BAAR_ESPUTO: 'Haemophilus influenzae',
        BIOPSIA: 'No',
        RESULTADO_BIOPSIA: '',
        OBSERVACION: 'Ingresa por insuficiencia respiratoria aguda.',
        DESTINO_PACIENTE: 'ALTA CON OXIGENO DOMICILIARIO',
        NUMERO_BIOPSIA: 'N/A',
        DATO_ADICIONAL_1: 'J44.1',
        DATO_ADICIONAL_2: 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda',
    }
];

const simulateDelay = (ms: number) => new Promise(res => setTimeout(res, ms));

export const fetchRecords = async (): Promise<PatientRecord[]> => {
    console.log("Simulating fetch...");
    await simulateDelay(500);
    // ORDEN REAL:
    // const response = await fetch(APPS_SCRIPT_URL);
    // const data = await response.json();
    // return data.slice(1).map((row: any[], index: number) => ({ /* Mapeo de columnas */ }));
    return [...mockData].sort((a, b) => new Date(b.FECHA).getTime() - new Date(a.FECHA).getTime());
};

export const addRecord = async (record: NewPatientRecord): Promise<void> => {
    console.log("Simulating add:", record);
    await simulateDelay(500);
    const newRecord: PatientRecord = { ...record, RowID: Date.now().toString() };
    mockData.push(newRecord);
    // ORDEN REAL:
    // await fetch(APPS_SCRIPT_URL, {
    //     method: 'POST',
    //     body: JSON.stringify({ action: 'create', data: record }),
    //     headers: { 'Content-Type': 'application/json' }
    // });
};

export const updateRecord = async (record: PatientRecord): Promise<void> => {
    console.log("Simulating update:", record);
    await simulateDelay(500);
    const index = mockData.findIndex(r => r.RowID === record.RowID);
    if (index !== -1) {
        mockData[index] = record;
    }
    // ORDEN REAL:
    // await fetch(APPS_SCRIPT_URL, {
    //     method: 'POST',
    //     body: JSON.stringify({ action: 'update', data: record }),
    //     headers: { 'Content-Type': 'application/json' }
    // });
};

export const deleteRecord = async (rowId: string): Promise<void> => {
    console.log("Simulating delete:", rowId);
    await simulateDelay(500);
    mockData = mockData.filter(r => r.RowID !== rowId);
    // ORDEN REAL:
    // await fetch(APPS_SCRIPT_URL, {
    //     method: 'POST',
    //     body: JSON.stringify({ action: 'delete', data: { RowID: rowId } }),
    //     headers: { 'Content-Type': 'application/json' }
    // });
};


// --- FIN DEL CÓDIGO DE SIMULACIÓN ---